sudo: false
before_script:
- mkdir /home/travis/bin
- export PATH="$PATH:/home/travis/bin"
branches:
  only:
  - master
script:
- pandoc --version
- make
- deploy.sh
addons:
  apt:
    packages:
    - pandoc
    - texlive-full
env:
  global:
  - secure: Zzei2HjdnfKeCPvb+56Y6R+43lb5YPLrPlIgb+qRQfmN8+jb5U+mLNPLUIAP2wP0jvYyVpEThcIVV4Hjd8X3EmL1W0CI3D++/aVZcYmo6e10J8ivfzExEBqjxckpu2D4YBJvKoIadYbaNSoC1PtWwUSkDchURmOW1t9WmZt8SAoH+ju04nyNEZOwY2GcOAkSCtmg707/Y3M9/SYCemt6yzu+2bJgzhBOvk9OtkQWNWMajLOBaDsyPS6BlrcmlK5yaDxToGRaMVY5DtdVlkHf4Za7XW8dS9W5zxpZmeVOUHdlx5Jw9w9x2/MP7YcC+eYkZDJC0O3GKKJSfxmqPjP16ECpL1Vv4e5kaY1TGJ69n7Av2WGE+wfqMwKY+Uwa0roEtt5El+E94Fu2HiTUcXZdDs0xiwqCE81HX/zjCunrKUz/23qN38Dh+EyQN5lWNFYBYIIS1St18CJhnnCzfYIxGKZOvA1TRv1a/8Wruf+afQonr8futj5PBaUrnRmSWX9jt3EWYI8p7wOBDAzMY8K6CRykvWW37q7y+/qhu0bOnHbeLkMbLO4F7fdpPTk7XdKOGSvj6Il0X+Ulv479kZsp6GpLvmryO6w/MADbDLWAfQ0D6nrD3zNMTIDTrn2LRe12mP8H8AkozavW1hjQRfDab5UE/akHyVC/kxb47oIJrh0=
