sudo: false
before_script:
- mkdir /home/travis/bin
- export PATH="$PATH:/home/travis/bin"
branches:
  only:
  - master
script:
- make
- deploy.sh
addons:
  apt:
    packages:
    - pandoc
    - texlive-full
env:
  global:
  - secure: mL3FaqtLcYAS7Jc/Grs/K2ppo6qM9yE8Dx7XU/JtBCA++UwE/oQ8SD5tf2RilPvYlkjb1WAH62epH9xKT1VVNzl5ccXbjXUkyufVi153jCQXi7NuijgV4bVHQkb0ZneJbcjxIe/60X+QHTdvF61cRUes8YSQV58ZcqUOC4eZyTQQ8qu0/eUasItkAaj5VgUj9UQ1JuDGFQCMey2Eciq+6G6BsO40kLPoY6uueN0tbFbdFNM6K5HQzj3jRJBElF5FMyT0BPTmJnhGOxMmUfG8/sJrdUOtFQHbRafk/JAKvWU7WNHCa+UUZsgMALd2n7HXs7GBmZXElpAXHHSV6CNBVYk+Y89D3inFrmDpgLsmt0aye2mkZMEyc6LsjPFlN2D3gVLXm4742WGGUQCffI19/y0tzpFAMfjtPkarhQnJEE3nYhobpxC+alrVPUg2DNHoDSxVFkifczCuqXDF4cZWt9c15QUBN6RFYN54EEMGqTvIePkTnXwlNTh45jialCUOqoTGoSRfJ9a8HzlC/8bgkrbrwrsC3duoNaroigHo4BL0yzF33YvJfK1z4t86eWGE7h9AGrKD2xcCr6czD9SA13Nbjw5TutbRobM0dCGefeYjUeVFe3irpoNOVa4P36EUXkUzyAzH2grpgYc8otI1ernIwjvhwvH5C/b9KrVaMlQ=
  - secure: FceJ+chJcxshVYe2BuBjg/2OpcpD3WD3m3TVys4vjmjjf7o4ypxyqXyfJVX5kf++gOMRyNqgY0m1IIVhw1OPmnYRkdg3C1FTKsSnl+het5vNAhUt2FEz12ngkGg/Jkd0CpgiN9M2TuO5OpWFP88pr0RtXiKKLOPFiD6n9cDNDKxM6gcsG+b1CqaORgP9eEvf9OZT2f4lkg16lpH5XmFEBK8j/le+saNTSkNdfdj2CBJNAnPUw8iFtxLYzZ2w0vSmFCfXxNJ+rkq/uFl/CanHqEoVqzJNNFzCUshm13oM9i8JXBM5Rn2DPI8ZZfjT6WjRg1wWOFWKIcKgucw9HF/JvdoN78BYihxWILOE51B7TF//hvAocnODih60lZDlD93CJd1OO069Z4fUsr9YZKDCk0e5MqRYTeRTuIyu+9wkOUkBCfHL1cfZi6Fm37GYbo6vEw3444Fb/zKfp/LltA7vQ5vjp9MRD9enyyPZWC9/Kc3KOFeeE8qkr9wbNqEYziTsvkWp1WF6VlLH8WUj4P/JYDv9o0EznA7sy/TJhRDUQRSFtX9ot0qzFFS7hnJfzCZSEVy2DlS6EKz4kAWJ4RUXcFLORnLftP2QrFKZy33B5U2qCL8gWYJogEdnkwkaA9lYynSQxI2DubcRtZ+7khhkT4zXKEDkvQFL6rn1cu2DJJg=
  - secure: Zzei2HjdnfKeCPvb+56Y6R+43lb5YPLrPlIgb+qRQfmN8+jb5U+mLNPLUIAP2wP0jvYyVpEThcIVV4Hjd8X3EmL1W0CI3D++/aVZcYmo6e10J8ivfzExEBqjxckpu2D4YBJvKoIadYbaNSoC1PtWwUSkDchURmOW1t9WmZt8SAoH+ju04nyNEZOwY2GcOAkSCtmg707/Y3M9/SYCemt6yzu+2bJgzhBOvk9OtkQWNWMajLOBaDsyPS6BlrcmlK5yaDxToGRaMVY5DtdVlkHf4Za7XW8dS9W5zxpZmeVOUHdlx5Jw9w9x2/MP7YcC+eYkZDJC0O3GKKJSfxmqPjP16ECpL1Vv4e5kaY1TGJ69n7Av2WGE+wfqMwKY+Uwa0roEtt5El+E94Fu2HiTUcXZdDs0xiwqCE81HX/zjCunrKUz/23qN38Dh+EyQN5lWNFYBYIIS1St18CJhnnCzfYIxGKZOvA1TRv1a/8Wruf+afQonr8futj5PBaUrnRmSWX9jt3EWYI8p7wOBDAzMY8K6CRykvWW37q7y+/qhu0bOnHbeLkMbLO4F7fdpPTk7XdKOGSvj6Il0X+Ulv479kZsp6GpLvmryO6w/MADbDLWAfQ0D6nrD3zNMTIDTrn2LRe12mP8H8AkozavW1hjQRfDab5UE/akHyVC/kxb47oIJrh0=
